package Multi_Threading.ThreadTest;

//Getting and Setting name of a thread.
//Every thread in java has some name it may be default name generated by jvm are customised a name proved by programmer.
//We can get and set name of a thread by using the following two methods of thread class -
// 1. public final String getName()
// 2. public final void String setName()

class Mythread extends Thread {
}
public class ThreadName {
    public static void main(String[] args) {
        System.out.println(Thread.currentThread().getName());
        Mythread t = new Mythread();
        System.out.println(t.getName());
        Thread.currentThread().setName("Duguu");
        System.out.println(Thread.currentThread().getName());

    }
}
